# -*- coding: utf-8 -*-
"""Day8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T4zkq1Ehi4IPD4VXJQDMTaKmi7Z477qb
"""

# STEP 1: Upload the CSV file
from google.colab import files
import pandas as pd

uploaded = files.upload()  # This will prompt you to upload 'train.csv'

# STEP 2: Load the data
df = pd.read_csv("train.csv")

# STEP 3: Convert date columns
df['Order Date'] = pd.to_datetime(df['Order Date'], format="%d/%m/%Y")
df['Ship Date'] = pd.to_datetime(df['Ship Date'], format="%d/%m/%Y")

# STEP 4: Handle missing postal codes
df['Postal Code'] = df['Postal Code'].astype('Int64')  # keep as nullable int
df['Postal Code'] = df['Postal Code'].fillna(-1).astype(int)  # or drop them if needed

# STEP 5: Remove duplicates
df.drop_duplicates(inplace=True)

# STEP 6: Feature engineering
df['Shipping Duration'] = (df['Ship Date'] - df['Order Date']).dt.days
df['Order Year'] = df['Order Date'].dt.year
df['Order Month'] = df['Order Date'].dt.month
df['Order Day'] = df['Order Date'].dt.day

# STEP 7: Convert postal code to string for analysis
df['Postal Code'] = df['Postal Code'].astype(str)

# STEP 8: Preview the cleaned DataFrame
df.head()

from google.colab import files

# Save the cleaned file
df.to_csv("train_cleaned.csv", index=False)

# Trigger the download
files.download("train_cleaned.csv")